pipeline:
  test:
   image: node:10
   commands:
     - printenv

  build:
    image: docker
    commands:
      - printenv
      - touch test.js
      - ls

  build-and-push:
    image: plugins/docker
    dockerfile: Dockerfile
    tags: latest
    repo: payers1/test
    build_args:
      - TEST=test

