pipeline:
  test:
   image: node:10
   commands:
     - printenv
     - yarn
    
  build:
    image: docker
    commands:
      - printenv

  build-and-push:
    image: plugins/docker
    commands:
      - printenv
      
