pipeline:
  test:
   image: node:10
   commands:
     - printenv

  build:
    image: docker
    commands:
      - printenv
      - docker version

  build-and-push:
    image: plugins/docker
    volumes: [ .:/test ]
    privileged: true
    commands:
      - ls

services:
  docker:
    image: docker:dind
    command: [ "--storage-driver=vfs", "--tls=false" ]
    privileged: true
