pipeline:
  test:
   image: node:10
   commands:
     - printenv

  build:
    image: docker
    commands:
      - printenv

  build-and-push:
    image: plugins/docker
    commands:
      - docker volume ls
