pipeline:
  test:
   image: node:10
   commands:
     - printenv

  build:
    image: docker
    commands:
      - printenv
      - docker version

  build-and-push:
    image: plugins/docker
    volumes: [ .:/test ]
    commands:
      - ls
